version: '3.3'


#Runs the custom docker image as well as a postgres image
#Runs the runserver command at the start
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment: 
      - OAUTHLIB_INSECURE_TRANSPORT = 1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
